### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by just-paja** [omegaui/omegaide#20]
Hello, this looks like a nice and challenging project. Wanted to test this out, but it starts so tiny, it is extremely difficult to make out how should I use it.

**Is your feature request related to a problem? Please describe.**
UI is unusable on 4K monitor

**Describe the solution you'd like**
Omega IDE should respect system configuration and scale accordingly

**Describe alternatives you've considered**
Alternative: Not use Omega IDE

**Additional context**

This is an actual screenshot of the window above this bug report.

![Snímek z 2022-03-19 22-10-48](https://user-images.githubusercontent.com/1508022/159138620-bfe695b5-e1a6-4f46-a7d2-df94eae04219.png)

Using gnome-41.3, I use Arch btw.

**Comment by omegaui** [comment]
Thanks for this issue!

I will take a look.

**Comment by omegaui** [comment]
@just-paja 

I looked into the matter and found that the incorrect scaling problem is arising from your monitor.

See,
I Tried setting the scale to 125%

![Screenshot 2022-03-20 170255](https://user-images.githubusercontent.com/73544069/159160219-e397f3b2-7aaa-49e1-8b67-38a2f7ecd090.png)

And to 100%

![Screenshot 2022-03-20 170159](https://user-images.githubusercontent.com/73544069/159160230-1416fbc9-027a-4a18-8ce3-9648a45f645f.png)


The IDE is responding correctly to scales.
May be its because of the font.

**Comment by omegaui** [comment]
Or May be this is related to gnome.
I am currently bound to use Windows 11, waiting for Ubuntu 22.04 to come out of the cave.

**Comment by just-paja** [comment]
I don't think this is a Gnome issue. Other apps scale just fine.

**Comment by omegaui** [comment]
I will take a look at implementing custom scaling
